### ISSUE TITLE
TS: Difference interface

### ISSUE THREAD

**Issue by renarsvilnis** [gliviu/dir-compare#14]
Hi,
thanks for the work on the library 🙇 

I'm integrating it in a personal app using typescript and noticed that that the `Difference` interface doesn't currently cover the actual result of the difference.

For example:

```
  {
    "path2": "/<base-path>/LUTs/ImpulZ Ultimate/ImpulZ Ultimate for Vision Color/29 ImpulZ -  Sony FS700 Cine 4",
    "relativePath": "/LUTs/ImpulZ Ultimate/ImpulZ Ultimate for Vision Color/29 ImpulZ -  Sony FS700 Cine 4",
    "name2": "Kodak Vision3 250D 5207 (NEG)_VS.cube",
    "state": "right",
    "type1": "missing",
    "type2": "file",
    "level": 4,
    "size2": 137798,
    "date2": "2014-05-30T16:54:26.000Z"
  }
```

Doesn't contain `name1`, `size1`, `date1` , equally for `"state": "right"`, there isn't a properties called `name2`, `size2`, `date2`.

I propose changing the typescript interface of all possible solutions to a union of a specific type of response based on state.

`interface Difference {..}` to `type Difference = DifferenceEqual | DifferenceLeft | DifferenceRight | DifferenceDistinct`

As a user of the library, I had a problem to understand that type of result combinations would I get depending on the state.

I still haven't caught a case when would I get a `"state": "distinct"` as `left` & `right` cover the "distinct" cases.

If using the only `state` property is a valid way of splitting up the differences, I'm ready to help with a PR.

### Update

Going through the library code understood that `state`:

- `left` - Entry is only present on the left side
- `right` - Entry is only present on the right side
- `equal` - Entry exists on both sides and depending on given options entries are considered "equal"
- `distinct` - Entry exists on both sides and depending on given option entries aren't considered "equal"

**Comment by renarsvilnis** [comment]
Added an initial split type definition #15 , let me know about any further changes.

**Comment by gliviu** [comment]
Thanks for reporting this problem. Now I see that what was obvious for me is indeed very confusing. And also the typing incorrectly indicates non-null values where null could occur at runtime.

I think your approach good for many usecases but I have some concerns it limits the usability of the diffset.
For example code below would not compile.
```javascript
var res = compareSync(path1, path2, options);
if(res.diffSet) {
  for(const diff of res.diffSet) {
    console.log(`left: ${diff.name1 || "N/A"}, right: ${diff.name2 || "N/A"}`); // compilation error: Property 'name1' does not exist on type 'Difference'.
  }
}
```
In order to make it compile I would have to do something like
```javascript
  for(const diff of res.diffSet) {
    console.log(`left: ${diff.state=='distinct'||diff.state=='equal'||diff.state=='left'?diff.name1:"N/A"}, right: ${diff.state=='distinct'||diff.state=='equal'||diff.state=='right'?diff.name2:"N/A"}}`);
  }
```
Or maybe I'm wrong and it could be done simpler than that. What do you think?

**Comment by renarsvilnis** [comment]
@gliviu

I do the explicit check for the side in my code as you show above.

Using `null` over `undefined` might be an option as the `diffSet` would then contain the keys but will "empty" `null` value.

But that would require actual library js code change :/

**Comment by gliviu** [comment]
What about using [optional properties](https://github.com/Microsoft/TypeScript/pull/7140#optional_parameters_and_properties).
```typescript
export interface Difference {
    path1?: string;  // shortcut for 'string | undefined'
    path2?: string;
    relativePath: string;
    name1?: string;
    name2?: string;
    state: DifferenceState;
    type1: DifferenceType;
    type2: DifferenceType;
    size1?: number;
    size2?: number;
    date1?: number;
    date2?: number;
    level: number;
}

function print(name1: String, name2: String) {
  console.log(`left: ${name1 || "N/A"}, right: ${name2 || "N/A"}`);
}

for(const diff of res.diffSet) {
  print(diff.name1, diff.name2)  // compile error because print(...) expect non-optional types 
}
```

It is not a perfect solution. I see it as middle point between flexibility and type safety.


> Using null over undefined might be an option as the diffSet would then contain the keys but will "empty" null value.

If I did get this right, optional properties allow us to use the 'undefined' properties without any additional .js change.
