### ISSUE TITLE
Unable to exclude paths from command line with globestar (**)

### ISSUE THREAD

**Issue by szpak** [gliviu/dir-compare#17]
I want to compare my mounted backup with the real directory to verify it's data integrity (that the backed up data are the same as the local). I started with the classic `diff`, but it doesn't support `**` in the exclusion patterns. `dir-compare` on the other hand uses `minimatch` which claims to do that. Unfortunately I wasn't able to make it works.

Simple case. I excluded the internal backup subdirectory (made by the problem itself) from external backup.

```
$ dircompare.js -c /home/foo/somepath/ /tmp/mounted-backup/
Entries are different
total: 326, equal: 26, distinct: 0, only left: 300, only right: 0
```

With `-a` I see that:
```
[/users/xxx/backup/20191019_151830] tasks.xml->missing
```

I can add `-x xxx` and it works, but that directory name could be reused in some other content, so I want to use globstar patterns which are also used by my backup tools (Borg backup). And this doesn't work:

```
$ dircompare.js -c -x "**/users/xxx/backup/**" /home/foo/somepath/ /tmp/mounted-backup/
Entries are different
total: 326, equal: 26, distinct: 0, only left: 300, only right: 0
```

How can I configure `dircompare.js` with `**`?

**Comment by szpak** [comment]
Looking at the `minimatch` execution in a debug mode when called from `dir-compare` it seems that only particular file names are compared, not the whole paths. Is there a way to use `dir-compare` with full path exclusion patterns?

**Comment by gliviu** [comment]
At the moment no. It is limited only to file names.
I'm thinking to add something like `--matchMode base|global`. If used with `global` it will apply minimatch to full path.
In the future we could expand it to more options.

**Comment by szpak** [comment]
I should handle the cases similar to mine. Let me know if you have any code to test :).

**Comment by gliviu** [comment]
Seems minimatch already has an option for matching by basename (what we had until now) and by full path.
> **matchBase**
> If set, then patterns without slashes will be matched against the basename of the path if it contains slashes. For example, a?b would match the path /xyz/123/acb, but not /xyz/acb/123.

Maybe we don't need a new `--matchMode` after all.

You can give it a try by checking out branch [17-glob-pattern](https://github.com/gliviu/dir-compare/tree/17-glob-pattern).

**Comment by gliviu** [comment]
Yes, Plus some documentation.
