### ISSUE TITLE
api doc of webpage is not available，I want to know which file is different

### ISSUE THREAD

**Issue by ruinuola** [gliviu/dir-compare#23]
I want to know which file is different

**Comment by gliviu** [comment]
[Api documentaion](https://gliviu.github.io/dc-api/) works well for me.
If you want to check differences in individual entries you can use [diffset](https://gliviu.github.io/dc-api/interfaces/result.html#diffset) in the result of a comparison.

Something like that.
```js
result.diffSet.forEach(dif => console.log('Difference - name1: %s, type1: %s, name2: %s, type2: %s, state: %s',
    dif.name1, dif.type1, dif.name2, dif.type2, dif.state))
```
Take a look at full example in [Usage](https://github.com/gliviu/dir-compare#use) section.
