### ISSUE TITLE
Ignore all whitespace differences

### ISSUE THREAD

**Issue by moshfeu** [gliviu/dir-compare#29]
Originally asked in https://github.com/moshfeu/vscode-compare-folders/issues/65

> I'm in desperate need of the ability to do some diffs on some project directories that should be very similar but have a lot of whitespace differences scattered around, making it impossible to easily figure out what's meaningfully different between them. Any chance you might be able to add something equivalent to running diff -b or diff -w?

> For the record, I have the ignoreWhiteSpaces option set which does ignore some whitespace differences like those at the start or end of a line, but that's it. It still shows differences in the number of newlines or whitespace differences in the middle of a line, like between a bracket and a comment.

@gliviu is it a reasonable feature?
Thanks

**Comment by gliviu** [comment]
See comment in original issue
