### ISSUE TITLE
Appears broken on Windows

### ISSUE THREAD

**Issue by kellyselden** [gliviu/dir-compare#3]
Here are my test results:

```
> node tests/runTests.js

test1: !!!!FAILED!!!!
test2: !!!!FAILED!!!!
test3: !!!!FAILED!!!!
test4: !!!!FAILED!!!!
test5: !!!!FAILED!!!!
test6: !!!!FAILED!!!!
test7: !!!!FAILED!!!!
test8: !!!!FAILED!!!!
test100: !!!!FAILED!!!!
test101: !!!!FAILED!!!!
test102: !!!!FAILED!!!!
test103: !!!!FAILED!!!!
test104: !!!!FAILED!!!!
test105: !!!!FAILED!!!!
test106: !!!!FAILED!!!!
test200: !!!!FAILED!!!!
test201: !!!!FAILED!!!!
test300: Passed
test301: Passed
test302: Passed
test303: Passed
test304: Passed
test400: !!!!FAILED!!!!
test500: !!!!FAILED!!!!
test501: !!!!FAILED!!!!
test600: !!!!FAILED!!!!
test601: !!!!FAILED!!!!

Tests: 27, failed: 22, succeeded: 5
```

**Comment by gliviu** [comment]
I assume you are using the latest version of dir-compare. If this is the case, could you follow these steps and attach report.txt to this issue?
```
git clone https://github.com/gliviu/dir-compare --branch report
cd dir-compare
npm install
node tests\runTests.js report
```
The file to attach can be found in dir-compare\tests\report.txt

**Comment by kellyselden** [comment]
[report.txt](https://github.com/gliviu/dir-compare/files/93680/report.txt)

**Comment by gliviu** [comment]
One problem is that newer versions of node seem to have changed String.localeCompare() so files result in different order. I fixed that.
But still there are other tests that fail and I don't know why because the output in report.txt is according to the expected value. I added some more debug log into report branch. Could you please fetch the changes and try again?

**Comment by kellyselden** [comment]
```
npm WARN Invalid version: "0.0.2-report-#3"
npm WARN EPACKAGEJSON dir-compare No description
npm WARN EPACKAGEJSON dir-compare No repository field.
npm WARN EPACKAGEJSON dir-compare No README data
npm WARN EPACKAGEJSON dir-compare No license field.
```

**Comment by kellyselden** [comment]
after fixing the version, here is the new report [report.txt](https://github.com/gliviu/dir-compare/files/104148/report.txt)

**Comment by gliviu** [comment]
That is very weird. It all boils down to line 44 in runTests.java
'''var res = output === expected;'''
This seems to be false even though 'output' and 'expected' are identical (as seen from report.txt).
I can't reproduce this on my environment but it would be helpful if you could add a breackpoint and see how these strings are reported different.

**Comment by gliviu** [comment]
If there are still problems with this, please reopen.

**Comment by kellyselden** [comment]
tested on v0.0.3 tag, still errors
[report.txt](https://github.com/gliviu/dir-compare/files/129839/report.txt)

**Comment by kellyselden** [comment]
I can't reopen, no button.

**Comment by gliviu** [comment]
Reopened. If you have the oportunity to debug this, it would be great as i can t reproduce on my environment. See my comment above on what the cause of the issue might be. If you need more info don't hesitate to send me an email.

**Comment by gliviu** [comment]
Most probably this was caused by Git windows settings 'Checkout Windows-style, commit Unit-style line endings' where expected test [results](https://github.com/gliviu/dir-compare/tree/v1.2.0/tests/expected) were converted to \r\n line endings that didn't match the actual result which is always \n.
