### ISSUE TITLE
ignoring empty directories

### ISSUE THREAD

**Issue by jillson** [gliviu/dir-compare#43]
My use case is looking at whether we need to do git operations by comparing a pair of directories as current and to-be states.  Recently ran into a problem where someone had created an empty directory in the to-be version, which caused dir-compare to (correctly) return that the directories were not the same, but then no git operations were needed (because git will ignore empty directories).  Bottom line:
  is there an option I'm missing that would allow me to tell dir-compare to ignore empty directories, and if not, is this something that would be worth me doing a PR for (vs what I'm going to do right now which is check the result sets after the fact)

**Comment by gliviu** [comment]
You are correct. There is no option for ignoring empty directories.
Don't worry about any PR. I'll add this option in the next few days.

**Comment by gliviu** [comment]
Until I create a new release you may try [this](https://github.com/gliviu/dir-compare/tree/43) branch with new `skipEmptyDirs` option.
```javascript
var options = {
    skipEmptyDirs: true,
    compareSize: true,
    compareContent: false,
}
var res = dircompare.compareSync(path1, path2, options);
```
