### ISSUE TITLE
fs.close no callback

### ISSUE THREAD

**Issue by olsonpm** [gliviu/dir-compare#5]
offending line: [fileDescriptorQueue:43](https://github.com/gliviu/dir-compare/blob/master/fileDescriptorQueue.js#L43)

```
fs.close(fd, callback); // <--------- callback is undefined here
```

Doesn't seem to affect functionality.  I only noticed due to node v7's warning

```
(node:48849) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

To reproduce

```sh
git clone https://github.com/olsonpm/dir-compare-deprecation.git
cd dir-compare-deprecation
npm i

# must have node 7 installed
nvm use node

node index

# outputs
# done
# (node:48849) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
# (node:48849) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

Since it doesn't affect functionality, I wasn't sure what the correct fix would be.  If you want, I can look into a fix as well.

Thanks for the module - it helped me out a lot :)

**Comment by gliviu** [comment]
That 'callback' should not really be missing. This is definitely a bug. If you have some time to check what is happening, that would be great.

**Comment by olsonpm** [comment]
Yeah - got a wedding this weekend but will definitely have time next week/end

**Comment by olsonpm** [comment]
Just looked at it now but got stumped when I couldn't figure out how the process was exiting mid tests

[this promise](https://github.com/gliviu/dir-compare/blob/master/tests/runTests.js#L794) is somehow causing process.exit to be called, but not from within your "git grep"able code.  I briefly looked into ways to get a stack trace from process.exit, but no luck.  I don't have the time to look in further.

**Comment by gliviu** [comment]
Yeah, I had a lot of headaches with promises hiding the stack trace. I'll give it a try myself.

**Comment by gliviu** [comment]
Thanks for support!!!
