### ISSUE TITLE
add ci tests

### ISSUE THREAD

**Issue by AndyOGo** [gliviu/dir-compare#8]
I suggest to Travis CI to automatically run your tests on `OS X` and `Linux` and AppVeyor to run your tests x86 and x64 Windows machines automatically.

**Comment by gliviu** [comment]
I usually run the tests on linux and win but for os x I have no chance. Travis sounds like a good option here.

**Comment by AndyOGo** [comment]
Yeah both travis and appveyor are awesome.
You can even supply environment matrices, mixing OS with different node versions.
And they automatically run on every commit, PR you push to github. It's really nice

**Comment by gliviu** [comment]
It will take some time to learn these tools but I'll give them a try.
